name: gvs
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - comm=0.2.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=7.0.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.0
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libsodium=1.0.20
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.5.4
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - prompt-toolkit=3.0.52
  - psutil=7.1.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - av==15.1.0
      - backcall==0.2.0
      - beautifulsoup4==4.14.2
      - bezier==2023.7.28
      - bleach==6.2.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.3.0
      - colorama==0.4.6
      - colorlog==6.9.0
      - contourpy==1.3.2
      - crc32c==2.7.1
      - cycler==0.12.1
      - defusedxml==0.7.1
      - diffusers==0.35.1
      - docopt==0.6.2
      - easydict==1.13
      - einops==0.8.1
      - facexlib==0.3.0
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - filterpy==1.4.5
      - fonttools==4.60.1
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - ftfy==6.3.1
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.75.1
      - h5py==3.14.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - imgaug==0.4.0
      - internetarchive==5.5.1
      - iopath==0.1.10
      - ipython==8.12.3
      - jaxtyping==0.3.3
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.9
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - lazy-loader==0.4
      - lightning==2.5.5
      - lightning-utilities==0.15.2
      - llvmlite==0.45.1
      - lmdb==1.7.3
      - lpips==0.1.4
      - markdown==3.9
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - mistune==3.1.4
      - moviepy==2.2.1
      - mpmath==1.3.0
      - multidict==6.6.4
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.4.2
      - numba==0.62.1
      - numpy==1.26.4
      - omegaconf==2.3.0
      - openai-clip==1.0.1
      - opencv-python==4.11.0.86
      - openexr==3.4.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parameterized==0.9.0
      - pillow==11.3.0
      - pipreqs==0.5.0
      - platformdirs==4.4.0
      - portalocker==3.2.0
      - proglog==0.1.12
      - propcache==0.3.2
      - protobuf==6.32.1
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pyglet==1.5.31
      - pyiqa==0.1.10
      - pyparsing==3.2.5
      - python-dotenv==1.1.1
      - pytorch-lightning==2.5.5
      - pytorchvideo==0.1.5
      - pytubefix==9.5.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.9.18
      - requests==2.32.5
      - roma==1.5.4
      - rotary-embedding-torch==0.8.9
      - rpds-py==0.28.0
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentry-sdk==2.39.0
      - shapely==2.1.2
      - smmap==5.0.2
      - soupsieve==2.8
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - tfrecord==1.14.6
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.15
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - tomli==2.2.1
      - torch==2.8.0
      - torch-fidelity==0.3.0
      - torchmetrics==0.11.4
      - torchvision==0.23.0
      - tqdm==4.67.1
      - transformers==4.57.0
      - triton==3.4.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wadler-lindig==0.1.7
      - wandb==0.22.1
      - wandb-osh==1.2.2
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - xformers==0.0.32.post2
      - yacs==0.1.8
      - yapf==0.43.0
      - yarg==0.1.9
      - yarl==1.20.1
      - zmq==0.0.0
