# @package _global_

# When the (dataset, experiment) pair aligns with the file name of this yaml, 
# the values here will override individual yamls files for dataset, algorithm and experiment.
# useful for dataset-specific overrides

dataset:
  resolution: 256
  latent:
    suffix: o7fbw6t8

algorithm:
  pretrained_path: checkpoints/vae/o7fbw6t8/model.ckpt

experiment:
  batch_size: 1
  validation:
    dataset_splits: [training, test]

